{
    'name': 'Loan Management',
    'version': '1.0',
    'summary': 'Manage loans, members, repayments and fines',
    'author': 'Aryan',
    'depends': ['base', 'mail','sale_management'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/loan_rules.xml',
        'data/sequence.xml',
        'wizard/payment_wizard_view.xml',
        'data/mail_template.xml', 
        'reports/loan_report_template.xml',
        'reports/loan_report.xml',
        'data/email_template.xml',
        'data/cron_jobs.xml',
        'views/loan_views.xml',
        'views/sale_order_view.xml',
        'views/sale_order_search_view.xml',
        'views/sale_order_action.xml',
    ],
    'installable': True,
    'application': True,
}
